---
abstract: "JAHERO's frequently-used or favorite modules\r"
author:
  - 'Jan Herout <jan.herout@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Task-BeLike-JAHERO-DO2
requires:
  App::Cmd: '0'
  Beam::Wire: '0'
  DBI: '0'
  DBIx::Simple: '0'
  DateTime: '0'
  File::Compare: '0'
  File::Find::Rule: '0'
  Log::Any: '0'
  Log::Any::Adapter: '0'
  Log::Any::Adapter::Log4perl: '0'
  Moo: '0'
  MooX::Role::Logger: '0'
  MooX::Types::Mooselike::Base: '0'
  Parse::CSV: '0'
  Path::Tiny: '0'
  Test2: '0'
  Test2::Suite: '0'
  Try::Tiny: '0'
  YAML::XS: '0'
version: '1.173490'
x_serialization_backend: 'YAML::Tiny version 1.69'
